// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthz": {
            "get": {
                "description": "Returns service health status and version",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/internal_api.HealthzResponse"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Returns current running service and api version",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "system"
                ],
                "summary": "Get Service Version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/github_com_lmriccardo_backer_deamon_internal_platform_version.Info"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_lmriccardo_backer_deamon_internal_platform_version.Info": {
            "type": "object",
            "properties": {
                "api": {
                    "type": "integer"
                },
                "commit": {
                    "type": "string"
                },
                "date": {
                    "type": "string"
                },
                "go_version": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "internal_api.HealthzResponse": {
            "type": "object",
            "properties": {
                "ok": {
                    "type": "boolean"
                },
                "version": {
                    "$ref": "#/definitions/github_com_lmriccardo_backer_deamon_internal_platform_version.Info"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Backer API",
	Description:      "Backup automation daemon API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
